{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "db81585c",
   "metadata": {},
   "source": [
    "# Filter sqlite database\n",
    "\n",
    "- TODO: execute this from worker to populate small tables for each commit\n",
    "- TODO: Better grouping for large exception texts that only slightly differ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d25e0c95",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlite3\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d8d409b2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "#records: 642998\n"
     ]
    }
   ],
   "source": [
    "con = sqlite3.connect(\"samples.sqlite3\")\n",
    "df = pd.read_sql_query(\"SELECT * from dewolf\", con)\n",
    "con.close()\n",
    "print(\"#records:\", len(df.index))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b8b5b0db",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 642998 entries, 0 to 642997\n",
      "Data columns (total 16 columns):\n",
      " #   Column                      Non-Null Count   Dtype  \n",
      "---  ------                      --------------   -----  \n",
      " 0   id                          642998 non-null  int64  \n",
      " 1   function_name               642998 non-null  object \n",
      " 2   function_basic_block_count  642998 non-null  int64  \n",
      " 3   function_size               642998 non-null  int64  \n",
      " 4   function_arch               642998 non-null  object \n",
      " 5   function_platform           642998 non-null  object \n",
      " 6   sample_hash                 642998 non-null  object \n",
      " 7   sample_name                 642998 non-null  object \n",
      " 8   dewolf_options              642998 non-null  object \n",
      " 9   dewolf_current_commit       642998 non-null  object \n",
      " 10  binaryninja_version         642998 non-null  object \n",
      " 11  dewolf_exception            231507 non-null  object \n",
      " 12  dewolf_traceback            231507 non-null  object \n",
      " 13  dewolf_decompilation_time   411491 non-null  float64\n",
      " 14  dewolf_undecorated_code     411491 non-null  object \n",
      " 15  is_successful               642998 non-null  int64  \n",
      "dtypes: float64(1), int64(4), object(11)\n",
      "memory usage: 78.5+ MB\n"
     ]
    }
   ],
   "source": [
    "df = df.drop_duplicates()\n",
    "df.info()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0697484f",
   "metadata": {},
   "source": [
    "# Failed decompilations (functions)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "5f397383",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "# failed runs: 231507\n"
     ]
    }
   ],
   "source": [
    "failed_runs = df[df.is_successful == 0]\n",
    "print(\"# failed runs:\", len(failed_runs.index))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "154b2367",
   "metadata": {},
   "source": [
    "## Exceptions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c9738c97",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unique exceptions: 80\n"
     ]
    }
   ],
   "source": [
    "print(\"Unique exceptions:\", len(failed_runs.dewolf_exception.unique()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e1ec85a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "224517: RuntimeError: 'NoneType' object has no attribute 'getInstructions'\n",
      "4727: AssertionError: Can not remove the root node!\n",
      "668: ValueError: The given set of variables is not an independent set. At least two variables interfere!\n",
      "610: RuntimeError: did not expect to reach canary check this way\n",
      "604: ValueError: Couldn't find target for type\n",
      "221: RuntimeError: argument of type 'NoneType' is not iterable\n",
      "18: AttributeError: 'MediumLevelILSyscallSsa' object has no attribute 'dest'\n",
      "14: ValueError: No switch variable candidate found.\n",
      "9: KeyError: 512\n",
      "8: OverflowError: cannot convert float infinity to integer\n",
      "6: KeyError: 224\n",
      "6: KeyError: 48\n",
      "5: AttributeError: 'MediumLevelILFunction' object has no attribute '_arch'\n",
      "5: KeyError: 24\n",
      "4: KeyError: 80\n",
      "4: RuntimeError\n",
      "4: KeyError: 96\n",
      "4: KeyError: 8\n",
      "4: ValueError: The children of Sequence can not be sorted due to circular reachability\n",
      "3: TypeError: 'NoneType' object is not iterable\n",
      "3: AttributeError: 'Branch' object has no attribute 'destination'\n",
      "2: KeyError: 56\n",
      "2: ctypes.ArgumentError: argument 1: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object\n",
      "2: ValueError: Did not expect a Constant/Unknown/Operation with more then 1 operand as a ForLoop declaration\n",
      "2: RuntimeError: Unexpected size 1\n",
      "1: ValueError: At least two variables in the identity group {var_58#2 (type: int aliased: True), var_58#4 (type: int aliased: True), var_58#0 (type: int aliased: True), var_58#8 (type: int aliased: True), var_58#7 (type: int aliased: True), var_58#6 (type: int aliased: True)} have out degree zero, namely var_58#7 and var_58#6, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {rax_14#6 (type: long aliased: False), rax_6#16 (type: long aliased: False), var_c0#0 (type: long aliased: False), var_c0#6 (type: long aliased: False), var_c0#2 (type: long aliased: False)} have out degree zero, namely rax_14#6 and rax_6#16, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_48#4 (type: char * aliased: False), var_48#0 (type: char * aliased: False), var_48#2 (type: char * aliased: False), var_48#12 (type: char * aliased: False), rax_1#3 (type: char * aliased: False), rdx#3 (type: char * aliased: False)} have out degree zero, namely var_48#4 and rax_1#3, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {0 type: long, rax_5#11 (type: long * aliased: False), var_1098#2 (type: long * aliased: False), var_1098#4 (type: long * aliased: False), var_1098#8 (type: long * aliased: False), var_1098#5 (type: long * aliased: False), var_1098#6 (type: long * aliased: False)} have out degree zero, namely 0x0 and rax_5#11, i.e., these set of vertices is not an identity group\n",
      "1: networkx.exception.NetworkXError: The node case 0x73: is not in the digraph.\n",
      "1: ValueError: At least two variables in the identity group {rbp_2#10 (type: DIR * aliased: False), rax_26#55 (type: DIR * aliased: False), rbp_2#8 (type: DIR * aliased: False), rax_26#54 (type: DIR * aliased: False), rax_26#56 (type: DIR * aliased: False), rbp_3#12 (type: DIR * aliased: False), rbx_5#14 (type: DIR * aliased: False), var_50#0 (type: DIR * aliased: False)} have out degree zero, namely rax_26#56 and rbx_5#14, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {arg6#4 (type: unsigned long aliased: False), arg6#2 (type: unsigned long aliased: False), arg4#0 (type: unsigned long aliased: False), var_70#0 (type: unsigned long aliased: False), arg4#11 (type: unsigned long aliased: False)} have out degree zero, namely arg6#2 and arg4#0, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {rax_27#20 (type: long aliased: False), rax_30#3 (type: long aliased: False), var_c0#2 (type: long aliased: False), var_c0#6 (type: long aliased: False), var_c0#0 (type: long aliased: False)} have out degree zero, namely rax_27#20 and rax_30#3, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_88#4 (type: void * aliased: False), var_88#2 (type: void * aliased: False), var_88#1 (type: void * aliased: False), var_88#0 (type: void * aliased: False), var_88#3 (type: void * aliased: False)} have out degree zero, namely var_88#2 and var_88#1, i.e., these set of vertices is not an identity group\n",
      "1: AssertionError: Node case \"add_to_previous_case\": is not in the AST.\n",
      "1: KeyError: 12468\n",
      "1: ValueError: At least two variables in the identity group {var_2048#0 (type: void aliased: True), var_2048#15 (type: void aliased: True), var_2048#21 (type: void aliased: True), var_2048#31 (type: void aliased: True), var_2048#33 (type: void aliased: True), var_2048#34 (type: void aliased: True), var_2048#13 (type: void aliased: True)} have out degree zero, namely var_2048#15 and var_2048#33, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_c8#54 (type: void aliased: True), var_c8#12 (type: void aliased: True), var_c8#14 (type: void aliased: True), var_c8#48 (type: void aliased: True), var_c8#59 (type: void aliased: True), var_c8#38 (type: void aliased: True), var_c8#9 (type: void aliased: True), var_c8#22 (type: void aliased: True), var_c8#18 (type: void aliased: True), var_c8#7 (type: void aliased: True), var_c8#23 (type: void aliased: True), var_c8#28 (type: void aliased: True), var_c8#26 (type: void aliased: True), var_c8#1 (type: void aliased: True), var_c8#44 (type: void aliased: True), var_c8#52 (type: void aliased: True), var_c8#36 (type: void aliased: True), var_c8#0 (type: void aliased: True), var_c8#4 (type: void aliased: True), var_c8#56 (type: void aliased: True), var_c8#40 (type: void aliased: True), var_c8#42 (type: void aliased: True)} have out degree zero, namely var_c8#48 and var_c8#18, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_50#3 (type: long() * aliased: False), arg4#3 (type: long() * aliased: False), var_50#0 (type: long() * aliased: False), rax_16#19 (type: long() * aliased: False), arg4#0 (type: long() * aliased: False), var_50#1 (type: long() * aliased: False)} have out degree zero, namely rax_16#19 and arg4#0, i.e., these set of vertices is not an identity group\n",
      "1: networkx.exception.NetworkXError: The node case 0x10: is not in the digraph.\n",
      "1: ValueError: At least two variables in the identity group {var_70#4 (type: unsigned long aliased: False), var_70#2 (type: unsigned long aliased: False), var_70#0 (type: unsigned long aliased: False), var_70#1 (type: unsigned long aliased: False), var_70#3 (type: unsigned long aliased: False)} have out degree zero, namely var_70#1 and var_70#3, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_50#18 (type: void * aliased: True), var_50#20 (type: void * aliased: True), var_50#7 (type: void * aliased: True), var_50#13 (type: void * aliased: True), var_50#9 (type: void * aliased: True), var_50#16 (type: void * aliased: True), var_50#0 (type: void * aliased: True), var_50#4 (type: void * aliased: True)} have out degree zero, namely var_50#18 and var_50#9, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_48#23 (type: unsigned long aliased: True), var_48#39 (type: unsigned long aliased: True), var_48#16 (type: unsigned long aliased: True), var_48#34 (type: unsigned long aliased: True), var_48#24 (type: unsigned long aliased: True), var_48#44 (type: unsigned long aliased: True), var_48#18 (type: unsigned long aliased: True), var_48#22 (type: unsigned long aliased: True), var_48#2 (type: unsigned long aliased: True), var_48#0 (type: unsigned long aliased: True), var_48#40 (type: unsigned long aliased: True), var_48#15 (type: unsigned long aliased: True), var_48#17 (type: unsigned long aliased: True), var_48#19 (type: unsigned long aliased: True), var_48#43 (type: unsigned long aliased: True), var_48#21 (type: unsigned long aliased: True), var_48#1 (type: unsigned long aliased: True), var_48#31 (type: unsigned long aliased: True), var_48#45 (type: unsigned long aliased: True), var_48#20 (type: unsigned long aliased: True), var_48#33 (type: unsigned long aliased: True), var_48#36 (type: unsigned long aliased: True), var_48#27 (type: unsigned long aliased: True), var_48#30 (type: unsigned long aliased: True), var_48#41 (type: unsigned long aliased: True)} have out degree zero, namely var_48#15 and var_48#27, i.e., these set of vertices is not an identity group\n",
      "1: networkx.exception.NetworkXError: The node case 0xe: is not in the digraph.\n",
      "1: KeyError: 104\n",
      "1: ValueError: list.remove(x): x not in list\n",
      "1: ValueError: At least two variables in the identity group {var_160#17 (type: long() * aliased: True), var_160#14 (type: long() * aliased: True), var_160#0 (type: long() * aliased: True), var_160#18 (type: long() * aliased: True), var_160#21 (type: long() * aliased: True), var_160#3 (type: long() * aliased: True), var_160#23 (type: long() * aliased: True)} have out degree zero, namely var_160#17 and var_160#21, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {rbx_2#5 (type: void * aliased: False), rbp_3#3 (type: void * aliased: False), rbp_3#4 (type: void * aliased: False), rbx_2#4 (type: void * aliased: False), var_50#0 (type: void * aliased: False)} have out degree zero, namely rbx_2#5 and rbp_3#4, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {rax_38#5 (type: long aliased: False), var_1f0#10 (type: long aliased: False), rax_32#29 (type: long aliased: False), var_1f0#2 (type: long aliased: False), rax_15#14 (type: long aliased: False), var_1f0#14 (type: long aliased: False), rax_24#45 (type: long aliased: False), var_1f0#6 (type: long aliased: False), var_1f0#0 (type: long aliased: False)} have out degree zero, namely rax_38#5 and rax_32#29, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_e0#1 (type: void * aliased: False), var_e0#4 (type: void * aliased: False), var_e0#2 (type: void * aliased: False), var_e0#0 (type: void * aliased: False), rax_51#57 (type: void * aliased: False)} have out degree zero, namely var_e0#1 and rax_51#57, i.e., these set of vertices is not an identity group\n",
      "1: networkx.exception.NetworkXError: The node case 0x3: is not in the digraph.\n",
      "1: ValueError: At least two variables in the identity group {var_438#6 (type: long aliased: True), var_438#13 (type: long aliased: True), var_438#0 (type: long aliased: True), var_438#4 (type: long aliased: True), var_438#11 (type: long aliased: True), var_438#19 (type: long aliased: True), var_438#3 (type: long aliased: True)} have out degree zero, namely var_438#6 and var_438#11, i.e., these set of vertices is not an identity group\n",
      "1: KeyError: TransitionBlock(-0x1, AST=var_1 = arg1)\n",
      "1: ValueError: At least two variables in the identity group {var_30#2 (type: long aliased: False), rax_6#23 (type: long aliased: False), var_30#6 (type: long aliased: False), var_30#0 (type: long aliased: False), rax_16#13 (type: long aliased: False)} have out degree zero, namely rax_6#23 and rax_16#13, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_60#14 (type: long * aliased: False), var_60#0 (type: long * aliased: False), rax_30#36 (type: long * aliased: False), var_60#10 (type: long * aliased: False), rax_24#25 (type: long * aliased: False), var_60#2 (type: long * aliased: False), var_60#6 (type: long * aliased: False), rax_38#13 (type: long * aliased: False), rax_16#47 (type: long * aliased: False)} have out degree zero, namely rax_30#36 and rax_24#25, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_d0#2 (type: long aliased: False), rax_13#23 (type: long aliased: False), rax_21#14 (type: long aliased: False), var_d0#0 (type: long aliased: False), var_d0#6 (type: long aliased: False)} have out degree zero, namely rax_13#23 and rax_21#14, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_30#2 (type: long aliased: False), var_30#6 (type: long aliased: False), rax_6#29 (type: long aliased: False), var_30#0 (type: long aliased: False), rax_16#19 (type: long aliased: False)} have out degree zero, namely rax_6#29 and rax_16#19, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {rax_14#24 (type: long * aliased: False), var_60#0 (type: long * aliased: False), rax_20#12 (type: long * aliased: False), var_60#2 (type: long * aliased: False), var_60#6 (type: long * aliased: False)} have out degree zero, namely rax_14#24 and rax_20#12, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_460#1 (type: void * aliased: False), var_460#4 (type: void * aliased: False), var_460#2 (type: void * aliased: False), var_460#5 (type: void * aliased: False), var_460#0 (type: void * aliased: False)} have out degree zero, namely var_460#1 and var_460#4, i.e., these set of vertices is not an identity group\n",
      "1: networkx.exception.NetworkXError: The node case 0x7: is not in the digraph.\n",
      "1: ValueError: At least two variables in the identity group {0 type: unsigned long, r12#1 (type: unsigned long aliased: False), var_60#6 (type: unsigned long aliased: False), var_60#0 (type: unsigned long aliased: False), var_60#4 (type: unsigned long aliased: False)} have out degree zero, namely 0x0 and r12#1, i.e., these set of vertices is not an identity group\n",
      "1: networkx.exception.NetworkXError: The node case 0x9: is not in the digraph.\n",
      "1: ValueError: At least two variables in the identity group {var_50#8 (type: unsigned long aliased: False), var_50#0 (type: unsigned long aliased: False), var_50#1 (type: unsigned long aliased: False), var_50#7 (type: unsigned long aliased: False), var_50#9 (type: unsigned long aliased: False), var_50#2 (type: unsigned long aliased: False)} have out degree zero, namely var_50#1 and var_50#7, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_30#2 (type: long aliased: False), var_30#6 (type: long aliased: False), var_30#0 (type: long aliased: False), rax_16#10 (type: long aliased: False), rax_24#28 (type: long aliased: False)} have out degree zero, namely rax_16#10 and rax_24#28, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {var_90#2 (type: long * aliased: False), var_90#4 (type: long * aliased: False), var_90#6 (type: long * aliased: False), rdi_1#3 (type: long * aliased: False), var_90#7 (type: long * aliased: False), var_90#0 (type: long * aliased: False)} have out degree zero, namely var_90#6 and rdi_1#3, i.e., these set of vertices is not an identity group\n",
      "1: KeyError: 40\n",
      "1: AssertionError: TrueNode must be a branch of if (!x3)\n",
      "1: ValueError: At least two variables in the identity group {r9_11#8 (type: char * aliased: False), var_70#0 (type: char * aliased: False), rcx_13#12 (type: char * aliased: False), var_70#4 (type: char * aliased: False), var_70#3 (type: char * aliased: False), var_70#6 (type: char * aliased: False), var_40_1#3 (type: char * aliased: False)} have out degree zero, namely r9_11#8 and rcx_13#12, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {r8#20 (type: unsigned long aliased: False), r8#16 (type: unsigned long aliased: False), r8#13 (type: unsigned long aliased: False), r8#6 (type: unsigned long aliased: False), r8#17 (type: unsigned long aliased: False)} have out degree zero, namely r8#6 and r8#17, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {arg3#2 (type: long aliased: False), var_40#0 (type: long aliased: False), var_40#2 (type: long aliased: False), arg3#0 (type: long aliased: False), rax_7#9 (type: long aliased: False)} have out degree zero, namely arg3#0 and rax_7#9, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {rax_28#44 (type: long aliased: False), var_a70#0 (type: long aliased: False), rax_20#25 (type: long aliased: False), var_a70#6 (type: long aliased: False), var_a70#10 (type: long aliased: False), rax_35#12 (type: long aliased: False), var_a70#2 (type: long aliased: False)} have out degree zero, namely rax_28#44 and rax_20#25, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {rax_24#16 (type: long aliased: False), var_30#2 (type: long aliased: False), rax_4#29 (type: long aliased: False), rax_14#5 (type: long aliased: False), var_30#6 (type: long aliased: False), var_30#10 (type: long aliased: False), var_30#0 (type: long aliased: False)} have out degree zero, namely rax_24#16 and rax_4#29, i.e., these set of vertices is not an identity group\n",
      "1: ValueError: At least two variables in the identity group {rax_13#4 (type: long aliased: False), var_30#2 (type: long aliased: False), rax_3#16 (type: long aliased: False), var_30#6 (type: long aliased: False), var_30#0 (type: long aliased: False)} have out degree zero, namely rax_13#4 and rax_3#16, i.e., these set of vertices is not an identity group\n",
      "1: AttributeError: 'NoneType' object has no attribute 'get_string_after_name'\n",
      "1: ValueError: At least two variables in the identity group {r8#13 (type: unsigned long aliased: False), r8#16 (type: unsigned long aliased: False), r8#6 (type: unsigned long aliased: False), r8#17 (type: unsigned long aliased: False), r8#20 (type: unsigned long aliased: False)} have out degree zero, namely r8#6 and r8#17, i.e., these set of vertices is not an identity group\n",
      "1: KeyError: TransitionBlock(-0x1, AST=var_0 = arg2)\n",
      "1: networkx.exception.NetworkXError: The node case 0xa: is not in the digraph.\n",
      "1: ValueError: At least two variables in the identity group {var_50#6 (type: long * aliased: False), var_50#0 (type: long * aliased: False), rax_28#15 (type: long * aliased: False), rax_13#3 (type: long * aliased: False), var_50#2 (type: long * aliased: False)} have out degree zero, namely rax_28#15 and rax_13#3, i.e., these set of vertices is not an identity group\n",
      "1: KeyError: 14813\n",
      "1: networkx.exception.NetworkXError: The node case 0x11: is not in the digraph.\n"
     ]
    }
   ],
   "source": [
    "for index, value in failed_runs.dewolf_exception.value_counts().items():\n",
    "    print(f\"{value}:\", index.strip())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "452de7cc",
   "metadata": {},
   "source": [
    "## Tracebacks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "89d04615",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unique tracebacks: 35\n"
     ]
    }
   ],
   "source": [
    "print(\"Unique tracebacks:\", len(failed_runs.dewolf_traceback.unique()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "3f485e6f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "224742:   File \"/opt/dewolf/decompiler/frontend/binaryninja/tagging.py\", line 30, in run\n",
      "    raise RuntimeError(e)\n",
      "4727:   File \"/opt/dewolf/decompiler/structures/graphs/rootedgraph.py\", line 87, in remove_node\n",
      "    assert node is not self.root, \"Can not remove the root node!\"\n",
      "668:   File \"/opt/dewolf/decompiler/structures/interferencegraph.py\", line 62, in contract_independent_set\n",
      "    raise ValueError(f\"The given set of variables is not an independent set. At least two variables interfere!\")\n",
      "610:   File \"/opt/dewolf/decompiler/pipeline/preprocessing/remove_stack_canary.py\", line 73, in _patch_branch_condition\n",
      "    raise RuntimeError(\"did not expect to reach canary check this way\")\n",
      "339:   File \"/opt/binaryninja/python/binaryninja/binaryview.py\", line 8463, in _value_helper\n",
      "    raise ValueError(\"Couldn't find target for type\")\n",
      "265:   File \"/opt/binaryninja/python/binaryninja/binaryview.py\", line 8463, in _value_helper\n",
      "    raise ValueError(\"Couldn't find target for type\")\n",
      "37:   File \"/opt/dewolf/decompiler/pipeline/dataflowanalysis/identity_elimination.py\", line 225, in find_replacement_variable_of_group\n",
      "    raise ValueError(message)\n",
      "25:   File \"/opt/dewolf/decompiler/pipeline/controlflowanalysis/variable_name_generation.py\", line 133, in _hungarian_prefix\n",
      "    prefix = self.type_prefix[type(var_type)][var_type.size]\n",
      "18:   File \"/opt/dewolf/decompiler/frontend/binaryninja/handlers/calls.py\", line 77, in _lift_call_parameter_names\n",
      "    clean_type_string_of_parameters = instruction.dest.expr_type.get_string_after_name().strip(\"()\")\n",
      "14:   File \"/opt/dewolf/decompiler/pipeline/preprocessing/switch_variable_detection.py\", line 117, in find_switch_expression\n",
      "    raise ValueError(\"No switch variable candidate found.\")\n",
      "13:   File \"/opt/dewolf/decompiler/pipeline/controlflowanalysis/variable_name_generation.py\", line 133, in _hungarian_prefix\n",
      "    prefix = self.type_prefix[type(var_type)][var_type.size]\n",
      "7:   File \"/opt/dewolf/.venv/lib/python3.10/site-packages/networkx/classes/digraph.py\", line 929, in predecessors\n",
      "    raise NetworkXError(f\"The node {n} is not in the digraph.\") from err\n",
      "5:   File \"/opt/binaryninja/python/binaryninja/mediumlevelil.py\", line 3081, in arch\n",
      "    return self._arch\n",
      "4:   File \"/opt/dewolf/.venv/lib/python3.10/site-packages/z3/z3.py\", line 2976, in _to_int_str\n",
      "    return str(int(val))\n",
      "3:   File \"/opt/dewolf/decompiler/structures/ast/ast_nodes.py\", line 284, in sort_children\n",
      "    raise ValueError(f\"The children of {self} can not be sorted due to circular reachability\")\n",
      "3:   File \"/opt/dewolf/decompiler/pipeline/preprocessing/compiler_idiom_handling.py\", line 92, in _get_replacement_instruction\n",
      "    return Assignment(instructions[last_index].destination, BinaryOperation(operation_type, [var, const]))\n",
      "2:   File \"/opt/dewolf/decompiler/pipeline/controlflowanalysis/readability_based_refinement.py\", line 451, in _get_variable_from_assignment\n",
      "    raise ValueError(\"Did not expect a Constant/Unknown/Operation with more then 1 operand as a ForLoop declaration\")\n",
      "2:   File \"/opt/dewolf/decompiler/frontend/binaryninja/parser.py\", line 50, in _add_basic_block_edges\n",
      "    lookup_table[edge.target.source_block.start],\n",
      "2:   File \"/opt/dewolf/decompiler/structures/ast/ast_nodes.py\", line 274, in children\n",
      "    if set(self._sorted_children) != set(children):\n",
      "2:   File \"/opt/dewolf/.venv/lib/python3.10/site-packages/z3/z3.py\", line 2976, in _to_int_str\n",
      "    return str(int(val))\n",
      "2:   File \"/opt/dewolf/.venv/lib/python3.10/site-packages/z3/z3.py\", line 2976, in _to_int_str\n",
      "    return str(int(val))\n",
      "2:   File \"/opt/dewolf/decompiler/pipeline/dataflowanalysis/array_access_detection.py\", line 295, in _size_in_bytes\n",
      "    raise RuntimeError(f\"Unexpected size {size}\")\n",
      "2:   File \"/opt/dewolf/.venv/lib/python3.10/site-packages/networkx/classes/coreviews.py\", line 81, in __getitem__\n",
      "    return AtlasView(self._atlas[name])\n",
      "2:   File \"/opt/dewolf/decompiler/structures/pseudo/typing.py\", line 155, in __str__\n",
      "    return self.SIZE_TYPES[self.size]\n",
      "1:   File \"/opt/dewolf/decompiler/structures/ast/ast_nodes.py\", line 284, in sort_children\n",
      "    raise ValueError(f\"The children of {self} can not be sorted due to circular reachability\")\n",
      "1:   File \"/opt/dewolf/decompiler/frontend/binaryninja/handlers/calls.py\", line 77, in _lift_call_parameter_names\n",
      "    clean_type_string_of_parameters = instruction.dest.expr_type.get_string_after_name().strip(\"()\")\n",
      "1:   File \"/opt/dewolf/decompiler/structures/pseudo/typing.py\", line 155, in __str__\n",
      "    return self.SIZE_TYPES[self.size]\n",
      "1:   File \"/opt/dewolf/decompiler/structures/ast/syntaxforest.py\", line 246, in extract_switch_from_condition_sequence\n",
      "    assert seq_node_branch.parent in condition_node.children, f\"{seq_node_branch} must be a branch of {condition_node}\"\n",
      "1:   File \"/opt/dewolf/decompiler/structures/pseudo/typing.py\", line 155, in __str__\n",
      "    return self.SIZE_TYPES[self.size]\n",
      "1:   File \"/opt/dewolf/decompiler/structures/ast/ast_nodes.py\", line 274, in children\n",
      "    if set(self._sorted_children) != set(children):\n",
      "1:   File \"/opt/dewolf/decompiler/structures/ast/syntaxgraph.py\", line 75, in parent\n",
      "    assert node in self, f\"Node {node} is not in the AST.\"\n",
      "1:   File \"/usr/lib/python3.10/ctypes/__init__.py\", line 510, in cast\n",
      "    return _cast(obj, obj, typ)\n",
      "1:   File \"/usr/lib/python3.10/ctypes/__init__.py\", line 510, in cast\n",
      "    return _cast(obj, obj, typ)\n",
      "1:   File \"/opt/dewolf/.venv/lib/python3.10/site-packages/networkx/classes/digraph.py\", line 929, in predecessors\n",
      "    raise NetworkXError(f\"The node {n} is not in the digraph.\") from err\n",
      "1:   File \"/opt/dewolf/decompiler/structures/graphs/basicblock.py\", line 155, in remove_instruction\n",
      "    self._instructions.remove(instruction)\n"
     ]
    }
   ],
   "source": [
    "for index, value in failed_runs.dewolf_traceback.value_counts().items():\n",
    "    print(f\"{value}:\", \"\\n\".join(index.strip().split(\"\\n\")[-2:]))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b6d15559",
   "metadata": {},
   "source": [
    "## Find 5 smallest cases per unique exception"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "45e51c20",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>function_name</th>\n",
       "      <th>function_basic_block_count</th>\n",
       "      <th>function_size</th>\n",
       "      <th>function_arch</th>\n",
       "      <th>function_platform</th>\n",
       "      <th>sample_hash</th>\n",
       "      <th>sample_name</th>\n",
       "      <th>dewolf_options</th>\n",
       "      <th>dewolf_current_commit</th>\n",
       "      <th>binaryninja_version</th>\n",
       "      <th>dewolf_exception</th>\n",
       "      <th>dewolf_traceback</th>\n",
       "      <th>dewolf_decompilation_time</th>\n",
       "      <th>dewolf_undecorated_code</th>\n",
       "      <th>is_successful</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>8</td>\n",
       "      <td>__stack_chk_fail</td>\n",
       "      <td>1</td>\n",
       "      <td>10</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>7690a63b03116527b8f3aa95625d36c44250bcbc3eb1d2...</td>\n",
       "      <td>7690a63b03116527b8f3aa95625d36c44250bcbc3eb1d2...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>AssertionError: Can not remove the root node!\\n</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>79</td>\n",
       "      <td>__stack_chk_fail</td>\n",
       "      <td>1</td>\n",
       "      <td>10</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>00d64368416328f6891235d725e605021d26eedbbf4f18...</td>\n",
       "      <td>00d64368416328f6891235d725e605021d26eedbbf4f18...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>AssertionError: Can not remove the root node!\\n</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>234</td>\n",
       "      <td>__stack_chk_fail</td>\n",
       "      <td>1</td>\n",
       "      <td>10</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>48ae6c2ee4c1fe9a072fe376bc66824eda5be072524793...</td>\n",
       "      <td>48ae6c2ee4c1fe9a072fe376bc66824eda5be072524793...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>AssertionError: Can not remove the root node!\\n</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>328</td>\n",
       "      <td>__stack_chk_fail</td>\n",
       "      <td>1</td>\n",
       "      <td>10</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>a46a30a17a093415db567c15b497d48ed9a4e56c41885f...</td>\n",
       "      <td>a46a30a17a093415db567c15b497d48ed9a4e56c41885f...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>AssertionError: Can not remove the root node!\\n</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>417</td>\n",
       "      <td>__stack_chk_fail</td>\n",
       "      <td>1</td>\n",
       "      <td>10</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>6cbd692bcbc3d8d4b7092bc1bd7d14a13df4f29e18402f...</td>\n",
       "      <td>6cbd692bcbc3d8d4b7092bc1bd7d14a13df4f29e18402f...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>AssertionError: Can not remove the root node!\\n</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>275</th>\n",
       "      <td>252511</td>\n",
       "      <td>ftdi_usb_open_string</td>\n",
       "      <td>39</td>\n",
       "      <td>728</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>121dfa46b9da0745086ac13444228802b83756741d3682...</td>\n",
       "      <td>121dfa46b9da0745086ac13444228802b83756741d3682...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>networkx.exception.NetworkXError: The node cas...</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>276</th>\n",
       "      <td>47095</td>\n",
       "      <td>sub_3da0</td>\n",
       "      <td>42</td>\n",
       "      <td>840</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>2cc4148bcdd7907a4aa9c8fa9a1b653cb6fe0c987f40fb...</td>\n",
       "      <td>2cc4148bcdd7907a4aa9c8fa9a1b653cb6fe0c987f40fb...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>networkx.exception.NetworkXError: The node cas...</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>277</th>\n",
       "      <td>54497</td>\n",
       "      <td>sub_6160</td>\n",
       "      <td>38</td>\n",
       "      <td>1016</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>96c1ecedc2e8ec7671b005b5c64e345604b1d39363383b...</td>\n",
       "      <td>96c1ecedc2e8ec7671b005b5c64e345604b1d39363383b...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>networkx.exception.NetworkXError: The node cas...</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>278</th>\n",
       "      <td>191785</td>\n",
       "      <td>sub_43b0</td>\n",
       "      <td>18</td>\n",
       "      <td>376</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>6207f05f2949ce3b51fce179729988b704de606045664b...</td>\n",
       "      <td>6207f05f2949ce3b51fce179729988b704de606045664b...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>networkx.exception.NetworkXError: The node cas...</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>279</th>\n",
       "      <td>566556</td>\n",
       "      <td>sub_3a90</td>\n",
       "      <td>20</td>\n",
       "      <td>374</td>\n",
       "      <td>x86_64</td>\n",
       "      <td>linux-x86_64</td>\n",
       "      <td>bc9c76c43330197b262edb75b7e5545789b9d352bdcd56...</td>\n",
       "      <td>bc9c76c43330197b262edb75b7e5545789b9d352bdcd56...</td>\n",
       "      <td>{\\n    \"expression-propagation.maximum_instruc...</td>\n",
       "      <td>b978d098f2a829650fb82e984bc7fd611c3190ea</td>\n",
       "      <td>3.1.3469</td>\n",
       "      <td>networkx.exception.NetworkXError: The node cas...</td>\n",
       "      <td>File \"/opt/dewolf/decompiler/util/bugfinder/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>280 rows × 16 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         id         function_name  function_basic_block_count  function_size   \n",
       "0         8      __stack_chk_fail                           1             10  \\\n",
       "1        79      __stack_chk_fail                           1             10   \n",
       "2       234      __stack_chk_fail                           1             10   \n",
       "3       328      __stack_chk_fail                           1             10   \n",
       "4       417      __stack_chk_fail                           1             10   \n",
       "..      ...                   ...                         ...            ...   \n",
       "275  252511  ftdi_usb_open_string                          39            728   \n",
       "276   47095              sub_3da0                          42            840   \n",
       "277   54497              sub_6160                          38           1016   \n",
       "278  191785              sub_43b0                          18            376   \n",
       "279  566556              sub_3a90                          20            374   \n",
       "\n",
       "    function_arch function_platform   \n",
       "0          x86_64      linux-x86_64  \\\n",
       "1          x86_64      linux-x86_64   \n",
       "2          x86_64      linux-x86_64   \n",
       "3          x86_64      linux-x86_64   \n",
       "4          x86_64      linux-x86_64   \n",
       "..            ...               ...   \n",
       "275        x86_64      linux-x86_64   \n",
       "276        x86_64      linux-x86_64   \n",
       "277        x86_64      linux-x86_64   \n",
       "278        x86_64      linux-x86_64   \n",
       "279        x86_64      linux-x86_64   \n",
       "\n",
       "                                           sample_hash   \n",
       "0    7690a63b03116527b8f3aa95625d36c44250bcbc3eb1d2...  \\\n",
       "1    00d64368416328f6891235d725e605021d26eedbbf4f18...   \n",
       "2    48ae6c2ee4c1fe9a072fe376bc66824eda5be072524793...   \n",
       "3    a46a30a17a093415db567c15b497d48ed9a4e56c41885f...   \n",
       "4    6cbd692bcbc3d8d4b7092bc1bd7d14a13df4f29e18402f...   \n",
       "..                                                 ...   \n",
       "275  121dfa46b9da0745086ac13444228802b83756741d3682...   \n",
       "276  2cc4148bcdd7907a4aa9c8fa9a1b653cb6fe0c987f40fb...   \n",
       "277  96c1ecedc2e8ec7671b005b5c64e345604b1d39363383b...   \n",
       "278  6207f05f2949ce3b51fce179729988b704de606045664b...   \n",
       "279  bc9c76c43330197b262edb75b7e5545789b9d352bdcd56...   \n",
       "\n",
       "                                           sample_name   \n",
       "0    7690a63b03116527b8f3aa95625d36c44250bcbc3eb1d2...  \\\n",
       "1    00d64368416328f6891235d725e605021d26eedbbf4f18...   \n",
       "2    48ae6c2ee4c1fe9a072fe376bc66824eda5be072524793...   \n",
       "3    a46a30a17a093415db567c15b497d48ed9a4e56c41885f...   \n",
       "4    6cbd692bcbc3d8d4b7092bc1bd7d14a13df4f29e18402f...   \n",
       "..                                                 ...   \n",
       "275  121dfa46b9da0745086ac13444228802b83756741d3682...   \n",
       "276  2cc4148bcdd7907a4aa9c8fa9a1b653cb6fe0c987f40fb...   \n",
       "277  96c1ecedc2e8ec7671b005b5c64e345604b1d39363383b...   \n",
       "278  6207f05f2949ce3b51fce179729988b704de606045664b...   \n",
       "279  bc9c76c43330197b262edb75b7e5545789b9d352bdcd56...   \n",
       "\n",
       "                                        dewolf_options   \n",
       "0    {\\n    \"expression-propagation.maximum_instruc...  \\\n",
       "1    {\\n    \"expression-propagation.maximum_instruc...   \n",
       "2    {\\n    \"expression-propagation.maximum_instruc...   \n",
       "3    {\\n    \"expression-propagation.maximum_instruc...   \n",
       "4    {\\n    \"expression-propagation.maximum_instruc...   \n",
       "..                                                 ...   \n",
       "275  {\\n    \"expression-propagation.maximum_instruc...   \n",
       "276  {\\n    \"expression-propagation.maximum_instruc...   \n",
       "277  {\\n    \"expression-propagation.maximum_instruc...   \n",
       "278  {\\n    \"expression-propagation.maximum_instruc...   \n",
       "279  {\\n    \"expression-propagation.maximum_instruc...   \n",
       "\n",
       "                        dewolf_current_commit binaryninja_version   \n",
       "0    b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469  \\\n",
       "1    b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "2    b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "3    b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "4    b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "..                                        ...                 ...   \n",
       "275  b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "276  b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "277  b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "278  b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "279  b978d098f2a829650fb82e984bc7fd611c3190ea            3.1.3469   \n",
       "\n",
       "                                      dewolf_exception   \n",
       "0      AssertionError: Can not remove the root node!\\n  \\\n",
       "1      AssertionError: Can not remove the root node!\\n   \n",
       "2      AssertionError: Can not remove the root node!\\n   \n",
       "3      AssertionError: Can not remove the root node!\\n   \n",
       "4      AssertionError: Can not remove the root node!\\n   \n",
       "..                                                 ...   \n",
       "275  networkx.exception.NetworkXError: The node cas...   \n",
       "276  networkx.exception.NetworkXError: The node cas...   \n",
       "277  networkx.exception.NetworkXError: The node cas...   \n",
       "278  networkx.exception.NetworkXError: The node cas...   \n",
       "279  networkx.exception.NetworkXError: The node cas...   \n",
       "\n",
       "                                      dewolf_traceback   \n",
       "0      File \"/opt/dewolf/decompiler/util/bugfinder/...  \\\n",
       "1      File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "2      File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "3      File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "4      File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "..                                                 ...   \n",
       "275    File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "276    File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "277    File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "278    File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "279    File \"/opt/dewolf/decompiler/util/bugfinder/...   \n",
       "\n",
       "     dewolf_decompilation_time dewolf_undecorated_code  is_successful  \n",
       "0                          NaN                    None              0  \n",
       "1                          NaN                    None              0  \n",
       "2                          NaN                    None              0  \n",
       "3                          NaN                    None              0  \n",
       "4                          NaN                    None              0  \n",
       "..                         ...                     ...            ...  \n",
       "275                        NaN                    None              0  \n",
       "276                        NaN                    None              0  \n",
       "277                        NaN                    None              0  \n",
       "278                        NaN                    None              0  \n",
       "279                        NaN                    None              0  \n",
       "\n",
       "[280 rows x 16 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "failed_runs.sort_values(\"function_size\").drop_duplicates(\"dewolf_exception\")\n",
    "\n",
    "\n",
    "filtered_df = failed_runs.groupby(\"dewolf_exception\").apply(lambda x: x.nsmallest(10, \"function_basic_block_count\"))\n",
    "filtered_df = filtered_df.reset_index(drop=True)\n",
    "filtered_df\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "d75eff90",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import sqlite3\n",
    "\n",
    "database_path = 'filtered.db'\n",
    "\n",
    "with sqlite3.connect(database_path) as conn:\n",
    "    # TODO: write to table 'commit'\n",
    "    filtered_df.to_sql('dewolf', conn, index=False, if_exists='replace')\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
